### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by mschoenebeck** [jwinterm/lightWallet#1]
When I try to start the client I get the following error:

```
$ python2.7 lightWallet.py 
[INFO   ] [Logger      ] Record log in /home/mschoenebeck/.kivy/logs/kivy_18-02-01_1.txt
[INFO   ] [Kivy        ] v1.9.0
[INFO   ] [Python      ] v2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609]
[INFO   ] [Factory     ] 173 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
 /usr/lib/python2.7/dist-packages/kivy/core/clipboard/clipboard_gtk3.py:14: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
   from gi.repository import Gtk, Gdk
[INFO   ] [Clipboard   ] Provider: gtk3(['clipboard_dbusklipper'] ignored)
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] OpenGL version <3.0 Mesa 17.2.4>
[INFO   ] [GL          ] OpenGL vendor <Intel Open Source Technology Center>
[INFO   ] [GL          ] OpenGL renderer <Mesa DRI Intel(R) Sandybridge Mobile >
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <1.30>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
 Traceback (most recent call last):
   File "lightWallet.py", line 842, in <module>
     lightWalletApp().run()
   File "/usr/lib/python2.7/dist-packages/kivy/app.py", line 798, in run
     root = self.build()
   File "lightWallet.py", line 834, in build
     root = RootWidget()
   File "lightWallet.py", line 485, in __init__
     self.daemon_server_textinput.text = daemon_URL
 AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by jwinterm** [comment]
This software hasn't been working or supported in years. Sorry.
